In [5]:
import numpy as np
from sklearn import datasets
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier


iris=datasets.load_iris()
iris_X=iris.data
iris_Y=iris.target
print(iris_X)
print(iris_Y)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

将iris_X,iris_Y分成X_train,X_test,Y_train,Y_test,其中X_test,Y_test占30%

分开后会打乱数据,有利于学习

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(iris_X,iris_Y,test_size=0.3)
print(Y_train)

[2 2 1 1 2 1 0 1 0 1 1 2 2 1 1 1 0 1 2 2 2 2 0 0 2 2 2 2 1 0 1 2 1 0 2 0 1
 0 1 0 2 1 0 0 0 0 0 1 0 2 2 0 0 2 2 2 2 2 1 0 1 0 0 0 0 2 1 0 0 1 1 1 2 2
 2 1 1 0 0 0 0 1 2 0 1 0 0 1 2 2 2 0 2 2 1 1 0 0 2 0 2 1 1 1 1]


将tarin数据使用knn训练

knn.perdict(X_test)  使用训练好的knn model(属性)来预测我的X_test数据的属性

In [14]:
knn=KNeighborsClassifier()
knn.fit(X_train,Y_train)
print(knn.predict(X_test))
print(Y_test)

[2 0 1 1 2 2 0 1 1 1 1 0 0 2 0 0 1 1 2 2 2 0 0 2 2 1 1 0 2 2 0 1 0 1 2 2 2
 0 1 0 0 2 2 2 1]
[1 0 1 1 2 2 0 1 1 1 1 0 0 2 0 0 1 1 2 2 1 0 0 2 2 1 1 0 2 2 0 1 0 1 2 2 2
 0 1 0 0 2 2 2 1]
