# Array(数组)
* rank

In [0]:
import numpy as np

In [0]:
a=np.array([1,2,3])

In [0]:
a

array([1, 2, 3])

In [0]:
type(a)

numpy.ndarray

In [0]:
a.shape

(3,)

shape [2,3] 表示为数组的意思是第一维有两个元素，第二维有三个元素，如: [[1,2,3],[4,5,6]]

In [0]:
a.reshape((1,-1))

array([[1, 2, 3]])

In [0]:
a=a.reshape((1,-1))  ##明确指定是行向量还是列向量,前面1表示这个数组只有一行,后面通过计算可以知道后面那个是3

```python
>>> z = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])

>>> print(z)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
>>> print(z.shape)
(4, 4)
>>> print(z.reshape(-1))
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
>>> print(z.reshape(-1,1))  #我们不知道z的shape属性是多少，
                            #但是想让z变成只有一列，行数不知道多少，
                            #通过`z.reshape(-1,1)`，Numpy自动计算出有16行，
                            #新的数组shape属性为(16, 1)，与原来的(4, 4)配套。
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]
>>> print(z.reshape(2,-1))
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
 ```

In [0]:
a.shape

(1, 3)

In [0]:
a=np.array([1,2,3,4,5,6])

In [0]:
a.shape

(6,)

In [0]:
a=a.reshape((2,-1))

In [0]:
a.shape

(2, 3)

In [0]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
a=a.reshape(-1,2)

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a.shape

(3, 2)

In [0]:
a[2,0]=55

In [0]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

zeros

In [0]:
a=np.zeros((3,3))

In [0]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ones

In [0]:
a=np.ones((3,3))

In [0]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

full

In [0]:
a=np.full((2,3),1)

In [0]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [0]:
a=np.full((3,3),0)

In [0]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

eye

In [0]:
a=np.eye(3)

In [0]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random.random

In [0]:
a=np.random.random((3,4))

In [0]:
a

array([[0.51209118, 0.79898874, 0.64334995, 0.93565003],
       [0.00954499, 0.24640369, 0.79607391, 0.64776208],
       [0.42480991, 0.8133123 , 0.61538481, 0.55905755]])

# indexing

In [0]:
a=np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]])

In [0]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [0]:
a=np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]])

In [0]:
a[-3:-1,0:2]

array([[1, 2],
       [5, 6]])

In [0]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
a.shape

(3, 4)

In [0]:
b=a[-2:,1:3]

In [0]:
 b.shape

(2, 2)

In [0]:
b=a[2,1:3]

In [0]:
b

array([10, 11])

In [0]:
b.shape

(2,)

In [0]:
b=a[1,2]

In [0]:
b

7

In [0]:
b.shape

()

In [0]:
b=a[2,1:3]

In [0]:
b

array([10, 11])

In [0]:
b.shape

(2,)

In [0]:
b=a[2:3,1:3]

In [0]:
b

array([[10, 11]])

In [0]:
b.shape

(1, 2)

得出结论,如果对数组取取整操作的话,导致数组维度-1

In [0]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [0]:
a[np.arange(3),1]+=10

In [0]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [0]:
np.arange(4)

array([0, 1, 2, 3])

In [0]:
np.arange(3,7)

array([3, 4, 5, 6])

In [0]:
np.arange(3,7).shape

(4,)

In [0]:
a[np.arange(3),[1,1,1]]+=10

In [0]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [0]:
a[[0,1,2],1]+=10

In [0]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [0]:
a[[0,1,2],[1,1,1]]+=10

In [0]:
a

array([[ 1, 42,  3,  4],
       [ 5, 46,  7,  8],
       [ 9, 50, 11, 12]])

In [0]:
result_index=a>10

In [0]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [0]:
aresult=a>10

In [0]:
aresult

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [0]:
a[aresult]

array([42, 46, 50, 11, 12])

In [0]:
a[a>10]

array([42, 46, 50, 11, 12])

# 元素数据类型

In [0]:
a=np.array([1,2])

In [0]:
a.dtype

dtype('int32')

In [0]:
a=np.array([1.1,2.2])

In [0]:
a.dtype

dtype('float64')

In [0]:
a=np.array([1,1.1])

In [0]:
a.dtype

dtype('float64')

In [0]:
a=np.array([2.4,5.7])

In [0]:
a=np.array([2.4,5.7],dtype=np.int64)

In [0]:
a

array([2, 5], dtype=int64)

In [0]:
a=np.array([2.4,5.7])

In [0]:
b=np.array(a,dtype=np.int64)

In [0]:
b

array([2, 5], dtype=int64)

In [0]:
a=np.array([2,5])

In [0]:
b=np.array(a,dtype=np.float64)

In [0]:
b

array([2., 5.])

# 数学运算与常用函数

In [0]:
a=np.array([[1,2],
           [3,4]])

In [0]:
b=np.array([[5,6],
           [6,5]])

In [0]:
a+b

array([[6, 8],
       [9, 9]])

In [0]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [0]:
a-b

array([[-4, -4],
       [-3, -1]])

In [0]:
np.subtract(a,b)

array([[-4, -4],
       [-3, -1]])

In [0]:
a*b

array([[ 5, 12],
       [18, 20]])

In [0]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [0]:
a/b

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [0]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [0]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [0]:
a

array([[1, 2],
       [3, 4]])

In [0]:
b=np.array([[1,2,3],
          [4,5,6]])

In [0]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [0]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [0]:
np.dot(b,a)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

# 常用函数
sum 求和

In [0]:
a

array([[1, 2],
       [3, 4]])

In [0]:
np.sum(a)

10

In [0]:
np.sum(a,axis=0) ##axis=0每一列进行求和操作

array([4, 6])

In [0]:
np.sum(a,axis=1) ##axis=1每一行进行求和操作

array([3, 7])

mean 求平均值

In [0]:
np.mean(a)

In [0]:
np.mean(a,axis=0)

array([2., 3.])

In [0]:
np.mean(a,axis=1)

array([1.5, 3.5])

uniform 用于产生随机数

In [0]:
np.random.uniform(3,4)

3.532784128977045

tile 将数组作为元素,重复指定的次数

In [0]:
a

array([[1, 2],
       [3, 4]])

In [0]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [0]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [0]:
np.tile(a,(3,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

argsort 用于将数组中的元素排序,返回数组中的索引值

In [0]:
a=np.array([[2,4,6,11],
           [5,8,6,2]])

In [0]:
a.argsort()

array([[0, 1, 2, 3],
       [3, 0, 2, 1]], dtype=int64)

In [0]:
a.argsort(axis=0)

array([[0, 0, 0, 1],
       [1, 1, 1, 0]], dtype=int64)

In [0]:
a.argsort(axis=1)

array([[0, 1, 2, 3],
       [3, 0, 2, 1]], dtype=int64)

理解:

In [0]:
x=np.array([2,3,4,5,-19,11])

In [0]:
y=np.argsort(x)

In [0]:
y

array([4, 0, 1, 2, 3, 5], dtype=int64)

这里我们可以看到argsort()函数是将x中的元素从小到大排列，提取其对应的index(索引号)

比如:最小的是x[4]=-19,所以y[0]=4

同理:最大的是x[5]=11,所以y[5]=5

下面是官方案例:
```python
 One dimensional array:一维数组

>>> x = np.array([3, 1, 2])
>>> np.argsort(x)
array([1, 2, 0])

Two-dimensional array:二维数组

>>> x = np.array([[0, 3], [2, 2]])
>>> x
array([[0, 3],
[2, 2]])

>>> np.argsort(x, axis=0) #按列排序
array([[0, 1],
[1, 0]])

>>> np.argsort(x, axis=1) #按行排序
array([[0, 1],
[0, 1]])

>>> x = np.array([3, 1, 2])
>>> np.argsort(x) #按升序排列
array([1, 2, 0])
>>> np.argsort(-x) #按降序排列
array([0, 2, 1])
>>> x[np.argsort(x)] #通过索引值排序后的数组
array([1, 2, 3])
>>> x[np.argsort(-x)]
array([3, 2, 1])
另一种方式实现按降序排序：

>>> a = x[np.argsort(x)]
>>> a
array([1, 2, 3])
>>> a[::-1]
array([3, 2, 1])
```

矩阵转置

In [0]:
a

array([[ 2,  4,  6, 11],
       [ 5,  8,  6,  2]])

In [0]:
a.T

array([[ 2,  5],
       [ 4,  8],
       [ 6,  6],
       [11,  2]])

In [0]:
np.transpose(a)

array([[ 2,  5],
       [ 4,  8],
       [ 6,  6],
       [11,  2]])

In [0]:
a= np.array([[3,6,4,11],[5,10,1,3]])

In [0]:
a.argsort()

array([[0, 2, 1, 3],
       [2, 3, 0, 1]], dtype=int64)

# 广播

In [0]:
a=np.array([[1,2,3],
            [5,6,8],
            [2,3,4],
            [33,42,1]])

In [0]:
b=np.array([1,2,3])

实现a的每一行与b相加

In [0]:
for i in range(4):
    a[i,:]+=b

In [0]:
a

array([[ 3,  6,  9],
       [ 7, 10, 14],
       [ 4,  7, 10],
       [35, 46,  7]])

In [0]:
a+np.tile(b,(4,1))

array([[ 4,  8, 12],
       [ 8, 12, 17],
       [ 5,  9, 13],
       [36, 48, 10]])

In [0]:
##广播就很简单了:
a+b

array([[ 4,  8, 12],
       [ 8, 12, 17],
       [ 5,  9, 13],
       [36, 48, 10]])

参考网上文章[通俗易懂的解释numpy中的广播](https://blog.csdn.net/xiang_freedom/article/details/77968164)

对两个数组，分别比较他们的每一个维度（若其中一个数组没有当前维度则忽略），满足：

- 当前维度的值相等
- 当前维度的值有一个是1

若条件不满足，抛出“ValueError: frames are not aligned”异常。 
输出数组的维度是每一个维度的最大值，广播将值为1的维度进行“复制”、“拉伸”，如图所示

![](https://graph-bed-1256708472.cos.ap-chengdu.myqcloud.com/image0020619.gif)